### ISSUE TITLE
subscript out of bounds using code template for light gbm

### ISSUE THREAD

**Issue by verajosemanuel** [RMHogervorst/templates_ml#2]
when using your code template for ligthgbm with tidymodels here 

https://github.com/RMHogervorst/templates_ml/blob/master/R/example_lightgbm.R

 I get an error (solved installing tree package)

```
1: All models failed. See the `.notes` column. 
]> lgbm_tuned$.notes
lgbm_tuned$.notes
[[1]]
# A tibble: 1 x 1
  .notes                                                           
  <chr>                                                            
1 internal: Error in pkg_list[[1]]: subscript out of bounds
```

SOLVED INSTALLING package tree
Thanks in advance

**Comment by RMHogervorst** [comment]
cool that you fixed it! All these packages are in active development, so it could very well be that my code no longer works because there are better ways now

**Comment by verajosemanuel** [comment]
yes, using lightgbm in tidymodels is a minefield. Issues every step. Now having random crashes....
